# Generated by Django 5.0 on 2024-02-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_location_created_alter_location_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
