# Generated by Django 5.0 on 2024-02-20 00:44

import address.models
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('pages', '0003_alter_location_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.address'),
        ),
    ]
