# Generated by Django 5.0 on 2024-02-20 01:30

import mapbox_location_field.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_location_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=mapbox_location_field.models.LocationField(map_attrs={}, null=True),
        ),
    ]
