# Generated by Django 5.0 on 2024-02-20 01:59

import mapbox_location_field.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_alter_location_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='location',
            name='longitude',
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=mapbox_location_field.models.LocationField(map_attrs={'center': [-71.1534, 42.35055], 'marker_color': 'blue', 'zoom': 13.4}, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(auto_created=True, blank=True, unique=True),
        ),
    ]
